from docx import Document

# Create a new Document
doc = Document()

# Title
doc.add_heading('Prenuptial Agreement', level=1)

# Intro
doc.add_paragraph(
    "This Prenuptial Agreement (\"Agreement\") is made and entered into this [Date] by and between:")

# Party 1 Details
doc.add_paragraph("Party 1:")
doc.add_paragraph("Name: [Full Name]")
doc.add_paragraph("Address: [Address]")
doc.add_paragraph("City, State, ZIP: [City, State, ZIP]")
doc.add_paragraph("(Hereinafter referred to as \"Party 1\")")

# Space
doc.add_paragraph()

# Party 2 Details
doc.add_paragraph("Party 2:")
doc.add_paragraph("Name: [Full Name]")
doc.add_paragraph("Address: [Address]")
doc.add_paragraph("City, State, ZIP: [City, State, ZIP]")
doc.add_paragraph("(Hereinafter referred to as \"Party 2\")")

# Space
doc.add_paragraph()

# Recitals
doc.add_heading('Recitals', level=2)
doc.add_paragraph(
    "A. Party 1 and Party 2 (collectively referred to as \"the Parties\") intend to marry each other on [Wedding Date].")
doc.add_paragraph("B. The Parties wish to define their respective rights and obligations regarding property, finances, and other matters during the marriage and in the event of a dissolution of the marriage, separation, or death.")

# Terms and Conditions
doc.add_heading('Terms and Conditions', level=2)

# Separate Property
doc.add_heading('1. Separate Property', level=3)
doc.add_paragraph(
    "1.1 Any property owned by either Party before the marriage, as listed in Exhibit A, shall remain the separate property of that Party.")
doc.add_paragraph(
    "1.2 Any gifts, inheritances, or bequests received by either Party during the marriage shall remain the separate property of that Party.")

# Marital Property
doc.add_heading('2. Marital Property', level=3)
doc.add_paragraph("2.1 Any property acquired by the Parties jointly during the marriage shall be considered marital property and subject to division upon dissolution of the marriage.")
doc.add_paragraph(
    "2.2 Any income or earnings generated by marital property shall be considered marital property.")

# Debts
doc.add_heading('3. Debts', level=3)
doc.add_paragraph(
    "3.1 Any debts incurred by either Party before the marriage shall remain the responsibility of that Party.")
doc.add_paragraph(
    "3.2 Any debts incurred jointly by the Parties during the marriage shall be the joint responsibility of both Parties.")

# Spousal Support
doc.add_heading('4. Spousal Support', level=3)
doc.add_paragraph(
    "4.1 In the event of a dissolution of the marriage, neither Party shall be entitled to spousal support from the other.")

# Waiver of Rights
doc.add_heading('5. Waiver of Rights', level=3)
doc.add_paragraph(
    "5.1 Each Party hereby waives any rights to the separate property of the other Party, as defined in this Agreement.")

# Full Disclosure
doc.add_heading('6. Full Disclosure', level=3)
doc.add_paragraph("6.1 The Parties acknowledge that they have made a full and fair disclosure of their respective financial situations, including assets, liabilities, and income.")

# Miscellaneous
doc.add_heading('7. Miscellaneous', level=3)
doc.add_paragraph(
    "7.1 This Agreement constitutes the entire agreement between the Parties and supersedes all prior agreements or understandings, whether written or oral.")
doc.add_paragraph(
    "7.2 Any modifications to this Agreement must be in writing and signed by both Parties.")
doc.add_paragraph(
    "7.3 This Agreement shall be governed by and construed in accordance with the laws of the State of [State].")

# Signatures
doc.add_heading('Signatures', level=2)
doc.add_paragraph("Party 1: ___________________________")
doc.add_paragraph("Date: ____________________________")
doc.add_paragraph("Party 2: ___________________________")
doc.add_paragraph("Date: ____________________________")

# Witnesses
doc.add_heading('Witnesses:', level=2)
doc.add_paragraph("Witness 1: _________________________")
doc.add_paragraph("Date: ____________________________")
doc.add_paragraph("Witness 2: _________________________")
doc.add_paragraph("Date: ____________________________")

# Save the document
file_path = r"C:\Users\KyleQ\Documents\Prenump\Prenuptial_Agreement_Draft.docx"
doc.save(file_path)

file_path
